### ISSUE TITLE
Problem: Some parts of the web app should be hidden pre-launch.

### ISSUE THREAD

**Issue by jalehman** [starcity-properties/starcity-web#132]
Signup should probably be hidden, since it's totally incomplete and doesn't do anything. Anything else?

I imagine that we'll probably need to remove the *Apply Now* button from the landing page in the meantime, and perhaps change *Join our Community* to do drive mailchimp signups.

Thoughts @msakrani ?

**Comment by msakrani** [comment]
I'm in support of the idea but do you think it'll be a time-suck to gate some pages and remove buttons/etc.?

I'd prefer we focus on completing the application ASAP if hiding stuff is time-consuming.
