### ISSUE TITLE
Task: Decide on a color scheme

### ISSUE THREAD

**Issue by jalehman** [starcity-properties/starcity-web#168]

**Comment by msakrani** [comment]
Alright, step one -- expanding the color palette based on our current palette:

Slate Blue (#53748c) -- I like the default and really like all of the "Lighten-#'s"

- Lighten-1: #5c819c
- Lighten-2: #6b8ea7
- Lighten-3: #7b9ab1
- Darken-1: #4a677c
- Darken-2: #40596c
- Darken-3: #374c5c

Cool Starcity Blue (#a1bed9) -- I like Darken-1 on this palette

- Lighten-1: #b3cbe0
- Lighten-2: #c5d7e8
- Lighten-3: #d7e4ef
- Darken-1: #8fb1d2
- Darken-2: #7da5ca
- Darken-3: #6b98c3

Orange (#e3a80d) -- I like the default and Lighten-1

- Lighten-1: #f2b618
- Lighten-2: #f3bd30
- Lighten-3: #f5c548
- Darken-1: #cb960c
- Darken-2: #b3840
- Darken-3: #9b7209

Bone Pink (#d7c2aa) -- I like Lighten-1 but we may need to replace this color

- Lighten-1: #dfcebb 
- Lighten-2: #e7dbcd
- Lighten-3: #efe7de
- Darken-1: #cfb699
- Darken-2: #c7a987
- Darken-3: #bf9d76

Green (#7a8e52) - I like Lighten-1

- Lighten-1: #889e5b
- Lighten-2: #94a96a
- Lighten-3: #a0b27a
- Darken-1: #6c7e49
- Darken-2: #5e6e34
- Darken-3: #505e36
