### ISSUE TITLE
Problem: No email communication after submission of application

### ISSUE THREAD

**Issue by jalehman** [starcity-properties/starcity-web#175]

**Comment by msakrani** [comment]
**From**: Starcity
**Subject**: We Are Processing Your Application

**Body**
Hi [First Name],

Thank you for completing Starcity's membership application. Here's what to expect now:

1. Over the next couple of business days, we'll process your application (community safety and financial checks) to pre-qualify you for the community.

2. We'll notify you as soon as you're pre-qualified, and one of our community members will reach out to schedule an interview and tour of the home you've applied for.

Stay tuned and thanks for your patience!

Best,
Team Starcity

**Comment by msakrani** [comment]
@jalehman per Jesse's request, can we please change the following:

1. _DELETE: Over the next couple of business _days,_ **We'll** process your application (community safety and financial checks) to pre-qualify you for the community. **We'll notify you as soon as you're pre-qualified.** (_Moved up from 2._)

2. One of our community members will then reach out to schedule an interview and tour of the home you've applied for.
