### ISSUE TITLE
Problem: Ellis, Mission, Turk have no description copy

### ISSUE THREAD

**Issue by jalehman** [starcity-properties/starcity-web#180]
The place to enter this information is somewhat obscure, so go ahead and leave it in a comment on this issue.

**Comment by msakrani** [comment]
West Soma:

"A victorian home designed to be welcoming and enjoyable, our West SoMa community offers members over 900 square feet in communal space. Members share a beautiful kitchen, social lounge, media room and more. Each member has their own private bedroom to nest in. The entire home is furnished to make moving in hassle-free. This community has five private units."

**Comment by msakrani** [comment]
Mission:

"An old single-room occupancy hotel and retail location, we've converted this building to offer our Mission community members over 1,000 square feet in communal space. Members share an industrial-sized kitchen with multiple cooking stations, a bar area, social lounges, media room and back storage. Members also have access to a back patio to soak in some sunshine. Each member gets their own private bedroom for rest and relaxation. As with all of our communities, all common and private areas are furnished for easy move-in. This community has 20 private units."

**Comment by msakrani** [comment]
Ellis:

"Our Union Square location is a four story, masonry structure completed in 1910. The building was built as a bathhouse and continued to be used as such until the mid-1980's. We're converting the top three floors into private units for our members and the ground-level offerings will be determined by the initial group of community members. Sign up now to be a part of building this community and having a say on the function of communal spaces! This community has room for 40 private units."

**Comment by msakrani** [comment]
Turk/Forge:

"This is a ground-up development in the historic Tenderloin neighborhood. It will offer 231 new housing units with lots of communal space. All units will have state of the art private baths and cooking facilities. Units will be approximately 250 square feet, 350 square feet, or 450 square feet. This project will be two, 7-story buildings adjacent to each other with 5,000 square feet of retail space on the ground. There will be shared roof decks and double height lounges on every other floor. We will implement state of the art green technologies with very low energy and water costs. Sign up now to have a say in the development of communal areas and to engage with early community members!"
