### ISSUE TITLE
Problem: Weird second menu sometimes visible in top left corner of screen

### ISSUE THREAD

**Issue by savvysuarez** [starcity-properties/starcity-web#219]
After signing up for an account, the navigation bar recreate itself as a scrollable menu in the top left corner of the screen. 
![weird menu](https://cloud.githubusercontent.com/assets/10428592/17313063/6a479fd4-580d-11e6-93fd-01e51222c85d.png)

**Comment by jalehman** [comment]
Browser?

**Comment by savvysuarez** [comment]
Chrome Version 51.0.2704.103 m
