### ISSUE TITLE
Problem: Sessions are not persisted between server restarts

### ISSUE THREAD

**Issue by savvysuarez** [starcity-properties/starcity-web#222]
I walked away while filling out my application and it booted me back to the login screen.  Once logging in, all my inputs were gone (not necessarily that taxing because I just clicked a few buttons) but it was an odd experience.  Typically there's a notice saying something like "For security, you have been logged out. Please log back in to continue."

**Comment by jalehman** [comment]
I don't time sessions out -- I'm guessing that this is actually due to a server restart in the middle of your application.

There have been a lot of fixes issued in the past hour. Will leave open for now as a reminder to prevent against this during future restarts.
