### ISSUE TITLE
Issue: Community Fitness Page

### ISSUE THREAD

**Issue by jondishotsky** [starcity-properties/starcity-web#229]
From Sofia Svensk,

"LOOKS GREAT! One issue...

After I filled out the community fitness page - it shot me back to the sign in page, when you hit sign in, it takes you back to community fitness again. Second time around it worked though, maybe just take a look at it to make sure. 

Let me know if I can help more!"

**Comment by jalehman** [comment]
Appears to be a duplicate of #222.
