### ISSUE TITLE
Problem: Microdeposits for Security Deposit Not Working

### ISSUE THREAD

**Issue by jondishotsky** [starcity-properties/starcity-web#328]
When I go through the micro deposit workflow, and press next it keeps loading for a long time. I have tried it multiple times now.

**Comment by jalehman** [comment]
This could be because it was your admin account that was approved, but will investigate. 

See comment in issue #329.

**Comment by jalehman** [comment]
@jondishotsky Could you try approving your application done from **jddishotsky@gmail.com**, and seeing if it works then?

**Comment by jondishotsky** [comment]
Yes. I still get the spiraling circle of death indefinitely. 
![screen shot 2016-10-27 at 3 27 01 pm](https://cloud.githubusercontent.com/assets/19414826/19787884/04f4fd02-9c5a-11e6-959b-bc8c4a06c16b.png)

**Comment by jondishotsky** [comment]
![screen shot 2016-10-27 at 4 08 44 pm](https://cloud.githubusercontent.com/assets/19414826/19788855/e62fef52-9c5f-11e6-835e-7a094f2fc0e8.png)

**Comment by jalehman** [comment]
@jondishotsky @msakrani This is temporarily resolved in production -- working on a long-term fix.

**Comment by jalehman** [comment]
Issue was related to loading of Stripe config keys prior to config file initialization, resulting in `nil` values. Fixed by using thunks (lambdas) to defer read of values until runtime.
