### ISSUE TITLE
Problem: Admin dashboard cannot be accessed by admins after they have approved themselves

### ISSUE THREAD

**Issue by msakrani** [starcity-properties/starcity-web#329]
unique to internal team -- cannot access admin dashboard and review applications once I'm "approved" and kicked into the onboarding flow.

**Comment by jalehman** [comment]
Will reset you to admin status.

**Comment by jalehman** [comment]
Issue has been rectified -- not going to build any hard solution to prevent this from happening in the future since I think we can just remember to not do this.
