### ISSUE TITLE
Problem: Security Deposit Amounts not customizable / not tied to rooms

### ISSUE THREAD

**Issue by msakrani** [starcity-properties/starcity-web#332]
We need to be able to customize the security deposit amount. For example, both Riccardo and Joe at West SoMa are in the two rooms that are not $2K / mo. Riccardo's private patio room at 6 month price = $2,500 / mo. and Joe's tiny room at 12 month price = $1,300 / mo.. I foresee this being an issue going forward with different room sizes, etc. 

We need to be able to set the security deposit amount at approval step of admin dashboard. 

ALTERNATIVELY, We should set pricing on a per-room basis at each building starting now. AND then approve individuals for particular rooms.

**Comment by jalehman** [comment]
The simpler approach for now will be to make the amount customizable. We'll have it default to the first month's rent at a building, and be overridable. This is easier for now, and can consider the alternative approach in the future when we have a way to work with "rooms".

**Comment by msakrani** [comment]
@jalehman cool, let's go w/ the simpler approach for now.
