### ISSUE TITLE
Remove the Month-To-Month Option and replace with 3 Month

### ISSUE THREAD

**Issue by jondishotsky** [starcity-properties/starcity-web#405]
@msakrani and I discussed removing month to month. Let's keep the price the same for the 3 month option but the length of stay likely needs to change on the back-end and on the website. 

We'll also need to change the wording in the FAQ after the question:
"How much does it cost?" to 3 months
"What is the length of a member's stay?" change: "We offer 3 month"

**Comment by jalehman** [comment]
@jondishotsky @msakrani I've changed the 1 month license to 3 months across the board -- those that applied with month-to-month now have 3 month terms selected. That alright?

**Comment by jondishotsky** [comment]
That's great @jalehman, the change is for people that apply in the future. So for Chris Kile, his application should still be month to month. But anyone new who applies can only go for 3 months, 6 months of 12 months.
