### ISSUE TITLE
Problem: CSS classes do not follow naming best-practices

### ISSUE THREAD

**Issue by jalehman** [starcity-properties/starcity-web#60]
When naming things, like CSS classes, it's ideal to visually separate multi-word names so that it's easier to read. For example:

```clojure
    [:div.homepage
     [:div.introsection
      [:div.introsignedout
       [:div.introcontent
    ;; ....
    ]]]]
```

Should look like this instead:

```clojure
    [:div.homepage
     [:div.intro-section
      [:div.intro-signed-out
       [:div.intro-content
    ;; ....
    ]]]]
```

This system of naming is called *kebab case*, and is preferred amongst lisp programmers (which we are!). Other systems that you'll see are:

- **Snake case:** `intro_section` (commonly used in C & JSON)
- **Camel case:** `introSection` (commonly used in most imperative languages)

Let's try and use consistent naming conventions throughout the entire application.

**Comment by msakrani** [comment]
no longer applicable.
